### ISSUE TITLE
What theme is it?

### ISSUE THREAD

**Issue by LeninZapata** [AkmarNafi/comment-headers#17]
Hello, it caught my attention that in the values ​​of an object it is shaded in a different color? Is it a theme or an extension that shadows a costom snippet?

Can you help me clear that doubt?
![image](https://github.com/user-attachments/assets/a3c69ef4-849f-4a0a-adea-f32756bedac6)

**Comment by AkmarNafi** [comment]
follow this to get inline hints, 
https://ash12rai-weblearning.medium.com/visual-studio-code-vs-code-inlay-hints-32fee837e80
ie  add `"typescript.inlayHints.parameterNames.enabled" : "all";` to .vscode > settings.json 

its not part of a theme, but a typescript setting in vscode. 
this is the theme though: https://marketplace.visualstudio.com/items?itemName=akmarnafi.midnight-code
